name: commit

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: commit
        run: |
          echo hello > world
          git add world
          (git commit -m message 2>&1) >> "$GITHUB_STEP_SUMMARY"
