name: commit

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: commit
        run: |
          echo hello > world
          git add world
          
          (
          if [ -z "$(git config user.name)" ]; then
            echo "no user.name - setting an example"
            git config user.name "example name" 2>/dev/null
          fi
          if [ -z "$(git config user.email)" ]; then
            echo "no user.email - setting an example"
            git config user.email "user@example.com" 2>/dev/null
          fi
          git commit -m message 2>&1 || true
          git show HEAD
          ) >> "$GITHUB_STEP_SUMMARY"
