name: commit

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: commit
        run: |
          echo hello > world
          git add world

          git config --global user.name "Global User"

          (
          # export GIT_COMMITTER_NAME="author name"
          export GIT_AUTHOR_EMAIL="committer@example.com"
          if [ -z "$(git config user.name)" ]; then
            echo "no user.name - setting an example"
            fallback_name="fallback name"
            if [ -z "$GIT_AUTHOR_NAME" ]; then
              export GIT_AUTHOR_NAME="$fallback_name"
            fi
            if [ -z "$GIT_COMMITTER_NAME" ]; then
              export GIT_COMMITTER_NAME="$fallback_name"
            fi
          fi

          if [ -z "$(git config user.email)" ]; then
            echo "no user.email - setting an example"
            fallback_email="fallback@example.com"
            if [ -z "$GIT_AUTHOR_EMAIL" ]; then
              export GIT_AUTHOR_EMAIL="$fallback_email"
            fi
            if [ -z "$GIT_COMMITTER_EMAIL" ]; then
              export GIT_COMMITTER_EMAIL="$fallback_email"
            fi
          fi
          git commit -m message 2>&1 || true
          echo '```'
          git show HEAD --format=full
          echo '```'
          ) >> "$GITHUB_STEP_SUMMARY"
